{% set name = "click-didyoumean" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00136c217f7fb2ab2999c272cfbd0c14cd2d6c7a643318a954357e2fc3ea7beb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6.2
  run:
    - click >=8.0.1,<9.0.0
    - python >=3.6.2,<4.0.0

test:
  requires:
    - pip
  imports:
    - click_didyoumean
  commands:
    - python -m pip check

about:
  home: https://github.com/timofurrer/click-didyoumean
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Enable git-like did-you-mean feature in click.

extra:
  recipe-maintainers:
    - duncanmmacleod
